// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNlb76WT8gd7UYgp9GaUu8ewLjsdxd_kM',
    appId: '1:836578180280:ios:e8c14fb0088e08f5a5084d',
    messagingSenderId: '836578180280',
    projectId: 'inkly-db436',
    storageBucket: 'inkly-db436.firebasestorage.app',
    iosBundleId: 'com.example.rohanFlutterSecondattempt',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNlb76WT8gd7UYgp9GaUu8ewLjsdxd_kM',
    appId: '1:836578180280:ios:e8c14fb0088e08f5a5084d',
    messagingSenderId: '836578180280',
    projectId: 'inkly-db436',
    storageBucket: 'inkly-db436.firebasestorage.app',
    iosBundleId: 'com.example.rohanFlutterSecondattempt',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5dt5w1z-d48b3L57es0docut4jZhidPc',
    appId: '1:836578180280:android:b88fa6c0f82ed19ba5084d',
    messagingSenderId: '836578180280',
    projectId: 'inkly-db436',
    storageBucket: 'inkly-db436.firebasestorage.app',
  );

}